# -*- coding: utf-8 -*-
"""credit_card_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rl4PtTiFfNdC-cSfNed2PWowXvPDix_j
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.neighbors import NearestNeighbors
try:
    df = pd.read_csv("creditcard.csv")
    print("Dataset loaded.")
except:
    print("creditcard.csv not found — creating simple synthetic dataset.")
    np.random.seed(42)
    df = pd.DataFrame({
        "V1": np.random.normal(0, 1, 2000),
        "V2": np.random.normal(0, 1, 2000),
        "Amount": np.random.exponential(50, 2000),
        "Class": np.random.choice([0, 1], 2000, p=[0.97, 0.03])   # 3% fraud
    })

print(df.head())
X = df[["V1", "V2", "Amount"]]
y = df["Class"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

model = LogisticRegression(class_weight="balanced")
model.fit(X_train, y_train)

print("\n=== MODEL EVALUATION ===")
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
knn = NearestNeighbors(n_neighbors=3)
knn.fit(X_scaled)
print("\n=== PREDICT A NEW TRANSACTION ===")
new_tx = np.array([[0.5, -1.2, 120]])
new_tx_scaled = scaler.transform(new_tx)

prediction = int(model.predict(new_tx_scaled)[0])
prob = float(model.predict_proba(new_tx_scaled)[0][1])

print("Predicted Class:", prediction, " (1 = fraud, 0 = legit)")
print("Probability of Fraud:", round(prob, 4))
distances, indices = knn.kneighbors(new_tx_scaled)
indices = indices[0]

print("\n=== SIMILAR PAST TRANSACTIONS (RAG) ===")
fraud_count = 0
for idx in indices:
    row = df.iloc[idx]
    print(f"V1={row.V1:.2f}, V2={row.V2:.2f}, Amount={row.Amount:.2f}, Class={row.Class}")
    fraud_count += row.Class
print("\n=== SIMPLE EXPLANATION ===")
if prediction == 1:
    print(" The model predicts this transaction is FRAUD.")
else:
    print(" The model predicts this transaction is LEGITIMATE.")

print(f"Among the 3 most similar past transactions, {fraud_count} were frauds.")

if fraud_count >= 2:
    print("Explanation: Similar transactions in history were mostly fraudulent, so risk is high.")
elif fraud_count == 1:
    print(" Explanation: A few similar past cases were fraud, so review is recommended.")
else:
    print(" Explanation: Historical similar cases were clean, so risk is low.")